Deck.find(7).cards << Card.create([
  {english: "airport", korean: "공항"},  
  {english: "airport immigration office", korean: "출입국관리소"},  
  {english: "passenger terminal", korean: "여객터미널"}, 
  {english: "baggage claim", korean: "수하물수취대"},
  {english: "customs inspection", korean: "세관검색대"}, 
  {english: "quarantine counter", korean: "검역소"}, 
  {english: "passport inspection (arrival)", korean: "입국여권심사대"}, 
  {english: "passport inspection (departure)", korean: "출국여권심사대"}, 
  {english: "security check", korean: "보안검색대"}, 
  {english: "check-in counter", korean: "체크인카운터"},  
  {english: "control tower", korean: "관제탑"}, 
  {english: "duty-free shop", korean: "면세점"}, 
  {english: "currency exchange", korean: "환전소"}, 
  {english: "gate", korean: "게이트"}, 
  {english: "lounge", korean: "라운지"}, 
  {english: "domestic air", korean: "국내선"}, 
  {english: "international air", korean: "국제선"}, 
  {english: "airline", korean: "항공"},  
  {english: "flight", korean: "운항"},  
  {english: "flight cancellation", korean: "결항"},  
  {english: "departure", korean: "출발"},  
  {english: "arrival", korean: "도착"},  
  {english: "delay", korean: "지연"},  
  {english: "route", korean: "노선"},  
  {english: "baggage", korean: "수하물"}, 
  {english: "boarding pass", korean: "탑승권"}, 
  {english: "airplane ticket", korean: "항공권"}, 
  {english: "passport", korean: "여권"},  
  {english: "visa", korean: "비자"},  
  {english: "arrival/departure card", korean: "출입국신고서"},  
  {english: "passenger", korean: "탑승객"}, 
  {english: "departing from a country", korean: "출국"},  
  {english: "entering a country", korean: "입국"},  
  {english: "boarding", korean: "탑승"},  
  {english: "transfer", korean: "환승"},  
  {english: "procedure (steps)", korean: "수속"},  
  {english: "one-way", korean: "편도"},  
  {english: "return (round) trip", korean: "왕복"},  
  {english: "airport limousine", korean: "공항리무진"}, 
  {english: "airplane", korean: "비행기"},
  {english: "aircraft", korean: "항공기"}, 
  {english: "customs officer", korean: "세관원"}, 
  {english: "customs", korean: "관세"}
])