Deck.find(5).cards << Card.create([

  {english: "clothes", korean: "옷"},
  {english: "tank top", korean: "탱크톱"},
  {english: "jeans", korean: "청바지"},
  {english: "shorts", korean: "반바지"},
  {english: "sandals", korean: "샌들"},
  {english: "shoes", korean: "신발"},
  {english: "sneakers", korean: "운동화"},
  {english: "high heels", korean: "하이힐"},
  {english: "leather jacket", korean: "가죽잠바"},
  {english: "wedding dress", korean: "웨딩드레스"},
  {english: "dress shoes", korean: "구두"},
  {english: "underwear", korean: "속옷"},
  {english: "jacket", korean: "재킷 / 잠바"},
  {english: "trousers", korean: "하의"},
  {english: "underwear", korean: "내복"},
  {english: "short sleeve", korean: "티셔츠 / 반팔"},
  {english: "long sleeve", korean: "긴팔"},
  {english: "sportswear", korean: "운동복"},
  {english: "uniform", korean: "제복"},
  {english: "wallet", korean: "지갑"},
  {english: "watch", korean: "시계"},
  {english: "pajamas", korean: "잠옷"},
  {english: "full dress", korean: "정장"},
  {english: "swimsuit", korean: "수영복"},
  {english: "suit", korean: "양복"},
  {english: "Korean traditional clothing", korean: "한복"},
  {english: "shirt", korean: "셔츠"},
  {english: "dress shirt", korean: "와이셔츠"},
  {english: "vest", korean: "조끼"},
  {english: "knitted clothes", korean: "니트"},
  {english: "cardigan", korean: "가디건"},
  {english: "sweater", korean: "스웨터"},
  {english: "blouse", korean: "블라우스"},
  {english: "coat", korean: "코트 / 오바"},
  {english: "parka", korean: "파카"},
  {english: "pants", korean: "바지"},
  {english: "cotton pants", korean: "면바지"},
  {english: "skirt", korean: "치마"},
  {english: "one-piece dress", korean: "원피스"},
  {english: "panties", korean: "팬티"},
  {english: "tie", korean: "넥타이"},
  {english: "glasses", korean: "안경"},
  {english: "hat", korean: "모자"},
  {english: "necklace", korean: "목걸이"},
  {english: "purse/handbag", korean: "핸드백"},
  {english: "ring", korean: "반지"},
  {english: "bra", korean: "브래지어"},
  {english: "socks", korean: "양말"},
  {english: "stockings", korean: "스타킹"},
  {english: "muffler", korean: "머플러"},
  {english: "sunglasses", korean: "썬글라스"},
  {english: "scarf", korean: "스카프/목도리"},
  {english: "hat", korean: "모자"},
  {english: "belt ", korean: "벨트"},
  {english: "gloves ", korean: "장갑"}

])