Deck.find(2).cards << Card.create([
  # {english: "economics (major)", korean: "경제학"}
  # {english: "high school", korean: "고등학교"},
  # {english: "community college", korean: "전문대학교"},
  # {english: "university/college", korean: "대학교"},
  # {english: "graduate school", korean: "대학원"},
  # {english: "kindergartner", korean: "유치원생"},
  # {english: "elementary school student", korean: "초등학생"},
  # {english: "middle school student", korean: "중학생"},
  # {english: "high school student", korean: "고등학생"},
  # {english: "college student", korean: "대학생"},
  # {english: "English", korean: "영어"},
  # {english: "literature", korean: "문학"},
  # {english: "grammar", korean: "문법"},
  # {english: "mathematics", korean: "수학"},
  # {english: "science", korean: "과학"},
  # {english: "history", korean: "역사"},
  # {english: "physics", korean: "물리"},
  # {english: "biology", korean: "생물"},
  # {english: "chemistry", korean: "화학"},
  # {english: "fine arts", korean: "미술"},
  # {english: "music", korean: "음악"},
  # {english: "physical education", korean: "체육"},
  # {english: "politics (major)", korean: "정치학"},
  # {english: "engineering", korean: "공학"},
  # {english: "education (major)", korean: "교육학"},
  # {english: "medicine (major)", korean: "의학"},
  # {english: "pharmacy (major)", korean: "약학"},
  # {english: "philosophy (major)", korean: "철학"},
  # {english: "psychology (major)", korean: "심리학"},
  # {english: "law (major)", korean: "법학"},
  # {english: "fashion (major)", korean: "의류학"},
  # {english: "graduation", korean: "졸업"},
  # {english: "class", korean: "수업"},
  # {english: "lecture", korean: "강의"},
  # {english: "attendance", korean: "출수"},
  # {english: "subject", korean: "과목"},
  # {english: "major", korean: "전공"},
  # {english: "exam", korean: "시험"},
  # {english: "score", korean: "성적"},
  # {english: "school vacation", korean: "방학"},
  # {english: "classroom", korean: "교실"},
  # {english: "playground", korean: "운동장"},
  # {english: "lecture hall/auditorium", korean: "강당"},
  # {english: "student", korean: "학생"},
  # {english: "teacher", korean: "선생님/교사"},
  # {english: "principal", korean: "교장"},
  # {english: "vice-principal", korean: "교감"},
  # {english: "textbook", korean: "교과서"},
  # {english: "homework", korean: "숙제"},
  # {english: "alumnus", korean: "동창"}
  ])