# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 017e679fca67d46a5bf3405973ab0356c78eec7eafec9425826a65af0d4b59f87ffe1cfc8105f0037cb05b4e411da10ad0ce503f18f8959e616ce56b41611805

test:
  secret_key_base: 2effb6aaf5141a8bf91639ef84aa2de4df842ed5898a66ca61514c7e440878ceb270e07f285d585d8f270f3637d5a2d90b2f0cd64d97902bfab2a66fd23f1429

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>